name: dollarx
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1 #[major][minor][patch][build]

environment:
  sdk: '>=3.2.3 <4.0.0'

  # To see which dependencies have newer
  # versions available, run `flutter pub outdated`.

  # To automatically upgrade your package dependencies to the latest versions
  # consider running `flutter pub upgrade --major-versions`.


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  # common
  flutter_svg: ^2.0.7
  bot_toast: ^4.1.3
  image_picker: ^1.0.4
  logger: ^2.0.2+1
  flutter_native_splash: ^2.3.2
  cached_network_image: ^3.3.0

  scroll_to_index: ^3.0.1
  rect_getter: ^1.1.0

  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  equatable: ^2.0.5
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  otp_text_field: ^1.1.3

  url_launcher: ^6.2.2
  fluttertoast: ^8.2.4
  flutter_image_compress: ^2.0.4
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.2.1


  # notifications
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^16.1.0


  # firebase
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/